# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# A minimal left prompt
format = """$sudo$directory$status$character"""

# move the rest of the prompt to the right
right_format = """$all"""

[aws]
format = '[$symbol($profile )(\($region\) )(\[$duration\] )]($style)'
symbol = " "

[buf]
symbol = " "

[c]
symbol = " "

[character]
success_symbol = '[➜](bold blue) '
error_symbol = '[➜](bold red) '

[cmd_duration]
disabled = false
format = '⌛ [$duration]($style) '
min_time = 1
show_notifications = true

[conda]
symbol = " "

[crystal]
symbol = " "

[dart]
symbol = " "

[directory]
read_only = " 🔒"
home_symbol = "🏠"
truncate_to_repo = false

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fennel]
symbol = " "

[fossil_branch]
symbol = " "

[git_branch]
symbol = " "

[git_commit]
tag_symbol = '  '

[git_status]
conflicted = "="
ahead =	"⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
up_to_date = " ✓ "
untracked = "?${count}"
stashed = ""
modified = "!${count}"
staged = "+${count}"
renamed = "»${count}"
deleted = " ${count}"

[golang]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[hostname]
ssh_symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[kotlin]
symbol = " "

# Let's see later if I want to enable this (currently too verbose for single line prompt)
[kubernetes]
disabled = true

[line_break]
disabled = true

[lua]
symbol = " "

[memory_usage]
disabled = false
symbol = " "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[ocaml]
symbol = " "

[os]
format = "[$symbol$version]($style)"

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[package]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[pijul_channel]
symbol = " "

[python]
symbol = " "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = "󱘗 "

[scala]
symbol = " "

[status]
disabled = false
symbol = " "

[sudo]
allow_windows = true
format = '[$symbol]($style)'
disabled = false

[swift]
symbol = " "

[time]
format = ' [$time]($style) '
disabled = false

[zig]
symbol = " "

[gradle]
symbol = " "
