name: "build"

on:
  push:
    branches:
      - master
      - feature/*
      - hotfix/*
  pull_request: {}
  workflow_call: {}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: cachix/install-nix-action@v27
        with:
          extra_nix_config: "access-tokens = github.com=${{ github.token }}"

      - name: Check flake evaluation
        run: nix flake check -L

      - name: Build server config
        run: nix build .#nixosConfigurations.maicol07-server.config.system.build.toplevel -L
